stages:
  - build
  - test
  - deploy

include:
  - project: "myfdweb/infrastructure/ci-templates"
    file: "/kaniko.yml"

create-pages:
  script:
    - cp -r html/ public/
  pages:
    publish: public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

build-image:
  extends: .kaniko
